In [456]:
import pandas as pd
import numpy as np

df = pd.read_csv("Dataset.csv")
df.head()

,ApplicantID,Gender,Married,Dependents,Education,SelfEmployed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,A001,Male,Yes,0,Graduate,No,4583,0,128,360,1,Urban,Approved
1,A002,Female,No,1,Not Graduate,Yes,3000,1500,66,360,0,Rural,Rejected
2,A003,Male,Yes,0,Graduate,No,2583,2358,120,360,1,Semiurban,Approved
3,A004,Male,Yes,2,Not Graduate,No,6000,0,141,360,,Urban,Approved
4,A005,Female,Yes,,Graduate,No,5417,4196,267,360,1,Urban,Approved

In [457]:
rows = df.shape[0]
columns = df.shape[1]
print(f"Rows : {rows}\nColumns : {columns}")

Rows : 435
Columns : 13

In [458]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ApplicantID        435 non-null    object
 1   Gender             435 non-null    object
 2   Married            435 non-null    object
 3   Dependents         321 non-null    object
 4   Education          435 non-null    object
 5   SelfEmployed       283 non-null    object
 6   ApplicantIncome    435 non-null    int64
 7   CoapplicantIncome  409 non-null    object
 8   LoanAmount         435 non-null    object
 9   Loan_Amount_Term   332 non-null    object
 10  Credit_History     258 non-null    object
 11  Property_Area      435 non-null    object
 12  Loan_Status        435 non-null    object
dtypes: int64(1), object(12)
memory usage: 44.3+ KB

In [459]:
# OBJECT TO INT OR FLOAT :CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History

In [460]:
df.isnull().sum()
df["Loan_Status"] = df["Loan_Status"].map({
    "Approved": 1,
    "Rejected": 0
})

In [461]:
df['Dependents'].unique()

array(['0', '1', '2', ' ', '3+', nan], dtype=object)

In [462]:
df['Dependents'] = df['Dependents'].replace('+3','3')
df['Dependents'] = df['Dependents'].replace(' ', np.nan)
df['Dependents'] = pd.to_numeric(df['Dependents'], errors='coerce')
df['Dependents'] = df['Dependents'].fillna(df["Dependents"].median())
df.head()

,ApplicantID,Gender,Married,Dependents,Education,SelfEmployed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,A001,Male,Yes,0.0,Graduate,No,4583,0,128,360,1,Urban,1
1,A002,Female,No,1.0,Not Graduate,Yes,3000,1500,66,360,0,Rural,0
2,A003,Male,Yes,0.0,Graduate,No,2583,2358,120,360,1,Semiurban,1
3,A004,Male,Yes,2.0,Not Graduate,No,6000,0,141,360,,Urban,1
4,A005,Female,Yes,1.0,Graduate,No,5417,4196,267,360,1,Urban,1

In [463]:
df['Dependents'] = df['Dependents'].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ApplicantID        435 non-null    object
 1   Gender             435 non-null    object
 2   Married            435 non-null    object
 3   Dependents         435 non-null    int64
 4   Education          435 non-null    object
 5   SelfEmployed       283 non-null    object
 6   ApplicantIncome    435 non-null    int64
 7   CoapplicantIncome  409 non-null    object
 8   LoanAmount         435 non-null    object
 9   Loan_Amount_Term   332 non-null    object
 10  Credit_History     258 non-null    object
 11  Property_Area      435 non-null    object
 12  Loan_Status        435 non-null    int64
dtypes: int64(3), object(10)
memory usage: 44.3+ KB

In [464]:
df["CoapplicantIncome"] = pd.to_numeric(df["CoapplicantIncome"], errors='coerce')
#df["CoapplicantIncome"] = df["CoapplicantIncome"].astype('int64')
df["CoapplicantIncome"] = df["CoapplicantIncome"].fillna(0)
df

,ApplicantID,Gender,Married,Dependents,Education,SelfEmployed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,A001,Male,Yes,0,Graduate,No,4583,0.0,128,360,1,Urban,1
1,A002,Female,No,1,Not Graduate,Yes,3000,1500.0,66,360,0,Rural,0
2,A003,Male,Yes,0,Graduate,No,2583,2358.0,120,360,1,Semiurban,1
3,A004,Male,Yes,2,Not Graduate,No,6000,0.0,141,360,,Urban,1
4,A005,Female,Yes,1,Graduate,No,5417,4196.0,267,360,1,Urban,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,A431,Female,Yes,2,Not Graduate,NaN,10300,0.0,229,360,NaN,Rural,1
431,A432,Male,No,2,Not Graduate,Yes,9475,2639.0,365,300,1,Urban,1
432,A433,Male,Yes,2,Graduate,NaN,2268,0.0,148,240,0,Semiurban,0
433,A434,Male,Yes,1,Not Graduate,No,12555,0.0,64,NaN,1,Urban,1
434,A435,Female,No,0,Not Graduate,NaN,8251,4060.0,344,300,NaN,Urban,1

In [465]:
df["CoapplicantIncome"].unique()

array([    0.,  1500.,  2358.,  4196.,  1516.,  2504., 10968.,   700.,
        8106.,  2840.,  3500.,  2253.,  1040.,  2925.,  1400.,  2033.,
        2669.,  1850.,  2667.,  1305.,  6733.,  6335.,  5963.,  2209.,
         555.,  3286.,  3908.,  6981.,   947.,  2518.,   537.,  6366.,
        3989.,  3894.,  5404.,  3397.,  6574.,  2242.,  2754.,  5808.,
        5357.,  3023.,  7708.,   185.,    44.,  2097.,  1980.,  1927.,
        1330.,  3711.,  3658.,   794.,  6216.,    91.,  1942.,  7368.,
        4076.,    65.,    73.,  5922.,  6032.,  5412.,  1998.,  1595.,
         644.,  1867.,  6588.,  4728.,   204.,   445.,  5918.,  6386.,
        2715.,  1672.,  3230.,  4492.,   275.,  6964.,  7960.,  4716.,
        6047.,  1666.,  3190.,  3724.,  5123.,  7700.,    67.,  4645.,
         849.,  3348.,  2404.,  1035.,  7678.,   885.,  1649.,  2644.,
        3255.,  2223.,  5256.,  1115.,  5569.,  2310.,  2267.,  5151.,
        3538.,   319.,  2997.,  1532.,   821.,   553.,  7992.,  3893.,
        7335.,  7672.,  6278.,  3357.,   733.,  6990.,  3719.,  1406.,
        2812.,  6045.,  1452.,  2758.,  4783.,  2436.,  3727.,  4981.,
        3931.,  2764.,  3041.,  2231.,  3970.,  6555.,   829.,  4238.,
        5356.,  3635.,   518.,   789.,   803.,  4137.,  4546.,  4816.,
         941.,  1026.,  3542.,  4039.,  1369.,  3660.,  3683.,  5514.,
        4486.,  4248.,  4500.,  1657.,  7225.,  6033.,  7243.,  7563.,
        6947.,   770.,  5327.,  2074.,  6065.,   511.,  4537.,  6052.,
        4259.,  2045.,  5458.,  6716.,  5163.,  5358.,  4146.,  3759.,
        2551.,  5359.,   492.,  2949.,  3774.,  7587.,  4819.,   857.,
        6659.,  6728.,  4886.,  5103.,  6174.,  5555.,  3457.,  1028.,
        2510.,  3659.,  1811.,  1804.,  4827.,  1523.,   408.,   746.,
        6643.,  7833.,  4962.,   101.,  3131.,  1674.,  2854.,  7034.,
         259.,  1956.,  3513.,  3204.,  6961.,  6989.,   156.,  3528.,
        1891.,  6608.,  7950.,  1226.,  6946.,  1358.,   231.,  4596.,
         191.,  7037.,    54.,  1439.,  7001.,  5072.,   778.,  6225.,
        2639.,  4060.])

In [466]:
df["LoanAmount"] = pd.to_numeric(df["LoanAmount"], errors='coerce')
df["LoanAmount"] = df["LoanAmount"].fillna(df["LoanAmount"].median())
df["LoanAmount"] = df["LoanAmount"].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ApplicantID        435 non-null    object
 1   Gender             435 non-null    object
 2   Married            435 non-null    object
 3   Dependents         435 non-null    int64
 4   Education          435 non-null    object
 5   SelfEmployed       283 non-null    object
 6   ApplicantIncome    435 non-null    int64
 7   CoapplicantIncome  435 non-null    float64
 8   LoanAmount         435 non-null    int64
 9   Loan_Amount_Term   332 non-null    object
 10  Credit_History     258 non-null    object
 11  Property_Area      435 non-null    object
 12  Loan_Status        435 non-null    int64
dtypes: float64(1), int64(4), object(8)
memory usage: 44.3+ KB

In [467]:
df["Credit_History"].unique()

array(['1', '0', ' ', nan], dtype=object)

In [468]:
df["Credit_History"] = pd.to_numeric(df["Credit_History"], errors='coerce')

In [469]:
df["Credit_History"].unique()

array([ 1.,  0., nan])

In [470]:
df["Credit_History"] = df["Credit_History"].fillna(0)
df["Credit_History"] = df["Credit_History"].astype('int64')
df.head()

,ApplicantID,Gender,Married,Dependents,Education,SelfEmployed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,A001,Male,Yes,0,Graduate,No,4583,0.0,128,360,1,Urban,1
1,A002,Female,No,1,Not Graduate,Yes,3000,1500.0,66,360,0,Rural,0
2,A003,Male,Yes,0,Graduate,No,2583,2358.0,120,360,1,Semiurban,1
3,A004,Male,Yes,2,Not Graduate,No,6000,0.0,141,360,0,Urban,1
4,A005,Female,Yes,1,Graduate,No,5417,4196.0,267,360,1,Urban,1

In [471]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ApplicantID        435 non-null    object
 1   Gender             435 non-null    object
 2   Married            435 non-null    object
 3   Dependents         435 non-null    int64
 4   Education          435 non-null    object
 5   SelfEmployed       283 non-null    object
 6   ApplicantIncome    435 non-null    int64
 7   CoapplicantIncome  435 non-null    float64
 8   LoanAmount         435 non-null    int64
 9   Loan_Amount_Term   332 non-null    object
 10  Credit_History     435 non-null    int64
 11  Property_Area      435 non-null    object
 12  Loan_Status        435 non-null    int64
dtypes: float64(1), int64(5), object(7)
memory usage: 44.3+ KB

In [472]:
df["Loan_Amount_Term"].unique()

array(['360', ' ', '180', nan, '240', '300'], dtype=object)

In [473]:
df["Loan_Amount_Term"] = pd.to_numeric(df["Loan_Amount_Term"], errors='coerce')
df["Loan_Amount_Term"] = df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].median())
df["Loan_Amount_Term"] = df["Loan_Amount_Term"].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ApplicantID        435 non-null    object
 1   Gender             435 non-null    object
 2   Married            435 non-null    object
 3   Dependents         435 non-null    int64
 4   Education          435 non-null    object
 5   SelfEmployed       283 non-null    object
 6   ApplicantIncome    435 non-null    int64
 7   CoapplicantIncome  435 non-null    float64
 8   LoanAmount         435 non-null    int64
 9   Loan_Amount_Term   435 non-null    int64
 10  Credit_History     435 non-null    int64
 11  Property_Area      435 non-null    object
 12  Loan_Status        435 non-null    int64
dtypes: float64(1), int64(6), object(6)
memory usage: 44.3+ KB

In [474]:
df["SelfEmployed"].unique()

array(['No', 'Yes', ' ', nan], dtype=object)

In [475]:
df["SelfEmployed"] = df["SelfEmployed"].str.strip()
df["SelfEmployed"] = df["SelfEmployed"].replace('',np.nan)
df["SelfEmployed"] = df["SelfEmployed"].fillna('No')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ApplicantID        435 non-null    object
 1   Gender             435 non-null    object
 2   Married            435 non-null    object
 3   Dependents         435 non-null    int64
 4   Education          435 non-null    object
 5   SelfEmployed       435 non-null    object
 6   ApplicantIncome    435 non-null    int64
 7   CoapplicantIncome  435 non-null    float64
 8   LoanAmount         435 non-null    int64
 9   Loan_Amount_Term   435 non-null    int64
 10  Credit_History     435 non-null    int64
 11  Property_Area      435 non-null    object
 12  Loan_Status        435 non-null    int64
dtypes: float64(1), int64(6), object(6)
memory usage: 44.3+ KB

In [476]:
#Checking Data if cleaned:

In [477]:
df["Total_Income"] = df["ApplicantIncome"] + df["CoapplicantIncome"]
df["Income_to_Loan_Ratio"] = df["Total_Income"] / (df["LoanAmount"] + 1)
df["Loan_Burden"] = df["LoanAmount"] / (df["Total_Income"] + 1)

for c in df.columns:
    print(f"Column :{c}")
    print(f"{df[c].unique()} \n")

Column :ApplicantID
['A001' 'A002' 'A003' 'A004' 'A005' 'A006' 'A007' 'A008' 'A009' 'A010'
 'A011' 'A012' 'A013' 'A014' 'A015' 'A016' 'A017' 'A018' 'A019' 'A020'
 'A021' 'A022' 'A023' 'A024' 'A025' 'A026' 'A027' 'A028' 'A029' 'A030'
 'A031' 'A032' 'A033' 'A034' 'A035' 'A036' 'A037' 'A038' 'A039' 'A040'
 'A041' 'A042' 'A043' 'A044' 'A045' 'A046' 'A047' 'A048' 'A049' 'A050'
 'A051' 'A052' 'A053' 'A054' 'A055' 'A056' 'A057' 'A058' 'A059' 'A060'
 'A061' 'A062' 'A063' 'A064' 'A065' 'A066' 'A067' 'A068' 'A069' 'A070'
 'A071' 'A072' 'A073' 'A074' 'A075' 'A076' 'A077' 'A078' 'A079' 'A080'
 'A081' 'A082' 'A083' 'A084' 'A085' 'A086' 'A087' 'A088' 'A089' 'A090'
 'A091' 'A092' 'A093' 'A094' 'A095' 'A096' 'A097' 'A098' 'A099' 'A100'
 'A101' 'A102' 'A103' 'A104' 'A105' 'A106' 'A107' 'A108' 'A109' 'A110'
 'A111' 'A112' 'A113' 'A114' 'A115' 'A116' 'A117' 'A118' 'A119' 'A120'
 'A121' 'A122' 'A123' 'A124' 'A125' 'A126' 'A127' 'A128' 'A129' 'A130'
 'A131' 'A132' 'A133' 'A134' 'A135' 'A136' 'A137' 'A138' 'A139' 'A140'
 'A141' 'A142' 'A143' 'A144' 'A145' 'A146' 'A147' 'A148' 'A149' 'A150'
 'A151' 'A152' 'A153' 'A154' 'A155' 'A156' 'A157' 'A158' 'A159' 'A160'
 'A161' 'A162' 'A163' 'A164' 'A165' 'A166' 'A167' 'A168' 'A169' 'A170'
 'A171' 'A172' 'A173' 'A174' 'A175' 'A176' 'A177' 'A178' 'A179' 'A180'
 'A181' 'A182' 'A183' 'A184' 'A185' 'A186' 'A187' 'A188' 'A189' 'A190'
 'A191' 'A192' 'A193' 'A194' 'A195' 'A196' 'A197' 'A198' 'A199' 'A200'
 'A201' 'A202' 'A203' 'A204' 'A205' 'A206' 'A207' 'A208' 'A209' 'A210'
 'A211' 'A212' 'A213' 'A214' 'A215' 'A216' 'A217' 'A218' 'A219' 'A220'
 'A221' 'A222' 'A223' 'A224' 'A225' 'A226' 'A227' 'A228' 'A229' 'A230'
 'A231' 'A232' 'A233' 'A234' 'A235' 'A236' 'A237' 'A238' 'A239' 'A240'
 'A241' 'A242' 'A243' 'A244' 'A245' 'A246' 'A247' 'A248' 'A249' 'A250'
 'A251' 'A252' 'A253' 'A254' 'A255' 'A256' 'A257' 'A258' 'A259' 'A260'
 'A261' 'A262' 'A263' 'A264' 'A265' 'A266' 'A267' 'A268' 'A269' 'A270'
 'A271' 'A272' 'A273' 'A274' 'A275' 'A276' 'A277' 'A278' 'A279' 'A280'
 'A281' 'A282' 'A283' 'A284' 'A285' 'A286' 'A287' 'A288' 'A289' 'A290'
 'A291' 'A292' 'A293' 'A294' 'A295' 'A296' 'A297' 'A298' 'A299' 'A300'
 'A301' 'A302' 'A303' 'A304' 'A305' 'A306' 'A307' 'A308' 'A309' 'A310'
 'A311' 'A312' 'A313' 'A314' 'A315' 'A316' 'A317' 'A318' 'A319' 'A320'
 'A321' 'A322' 'A323' 'A324' 'A325' 'A326' 'A327' 'A328' 'A329' 'A330'
 'A331' 'A332' 'A333' 'A334' 'A335' 'A336' 'A337' 'A338' 'A339' 'A340'
 'A341' 'A342' 'A343' 'A344' 'A345' 'A346' 'A347' 'A348' 'A349' 'A350'
 'A351' 'A352' 'A353' 'A354' 'A355' 'A356' 'A357' 'A358' 'A359' 'A360'
 'A361' 'A362' 'A363' 'A364' 'A365' 'A366' 'A367' 'A368' 'A369' 'A370'
 'A371' 'A372' 'A373' 'A374' 'A375' 'A376' 'A377' 'A378' 'A379' 'A380'
 'A381' 'A382' 'A383' 'A384' 'A385' 'A386' 'A387' 'A388' 'A389' 'A390'
 'A391' 'A392' 'A393' 'A394' 'A395' 'A396' 'A397' 'A398' 'A399' 'A400'
 'A401' 'A402' 'A403' 'A404' 'A405' 'A406' 'A407' 'A408' 'A409' 'A410'
 'A411' 'A412' 'A413' 'A414' 'A415' 'A416' 'A417' 'A418' 'A419' 'A420'
 'A421' 'A422' 'A423' 'A424' 'A425' 'A426' 'A427' 'A428' 'A429' 'A430'
 'A431' 'A432' 'A433' 'A434' 'A435']

Column :Gender
['Male' 'Female']

Column :Married
['Yes' 'No']

Column :Dependents
[0 1 2]

Column :Education
['Graduate' 'Not Graduate']

Column :SelfEmployed
['No' 'Yes']

Column :ApplicantIncome
[ 4583  3000  2583  6000  5417  2333  3036  4006 12841  3200  2500  3073
  1853  4400  7660  2600  2799  4226  1442  3750  3500  3100  2253  4416
 10750  2100  3887  4600  5667  4500  2400  3800  5000  7970  6876  5564
 11734 10481 14848  7178 11447 12618  3794  5782  9316  9168 13329 12596
  8532  2285  6170 12492 12094  2584 14021 14587  6001 14750  1525  1741
  4286 14301 13648  8996  5251  9866 13833  5639  5628  8741  1567 11162
  2260 11188  8147  3080 13882 13766  2440  4091  7310  2357 12295  4296
 12231  9037  1507  4651  3721 11911  7673 10401  6975  5686 10982  5814
  6692  2988  4233  8734 13324  4829 14594  3243 12988 12107 13181  2598
  9193  4108  9820  1902  7853  1906  3258 13187 12735  5192 12145 12025
  1759 10402 10288  5146 11228  5404  4362 14865  8899  9256 14797 10880
 10257  6643  3384  9052  7681 11451  3302  3550  7838  5757 11660 13885
 14452  4298 12078  2153  4679  7646 10521 13727 11545 14031  2689 11136
 12142 11351 12022  3435  3303  4473  7077  2068  3843 11863  8252 10964
  5382  6266  8065 10659  6018 13908 10315 13129 13417  4976  9465  5355
  2413 13337 13416  4453 14459 11597  4469  5094  2589  5015  7616  5485
 11270 14952  8578 10604  6024 11258  5152  7638  5376 14607 10895  7071
  8895  2793  2143  2742 13019 12780  6393 11499  3355 13340  8341 14286
  6632  5680 10720 12819 14690 12703  3737 11328  7317  9584 13197  2166
  6641 13065  5044 12870  9640  9699 12451  4890  6523  7548 14912  8813
  4067  3601  4301  3429 14976  4150  3886  4681 14114 11814  3621 13752
 11276 14464 13556  2088 14072  5877 10049  6734  5480  8440  7791 12332
  4122  7988 13442  1653  8111 13588  4015 11561 13871 13543  2520 12052
  1821  8539  2305 12850  3718  1520  5407 14852  6653  2163 13006  3409
 10104 14719 12895 10868 12506  3683 11559 14583  9427  6831  6505 12302
 10044  9413 13515 14991  2354  2668  6051  2919  7499 14080  5552  9896
  9864 11301 14335  7130  9809  2929 11651  2032 14440  5731  2972  4620
  4012  8655  5222  2900  9156  7074  2451 12876  1789 13542 12695  7140
  8224  2587  7727  2280 12508 14758 14792 10170  8849  5240  3517  4824
  5960  2250 13669 12260 10581  5651  8692 11466 12001  3929  9226  7987
 14044  6514  6979  5613  7728 12322  5585 12455  3908 10302  3350  2303
  6462  4132  2605  2208  7634  9513  6772  7974  8286  7680  3069  4991
  4491 11398 12426  4081  7383  4472  7537  9613  2561  1696  3402  6965
  6525  2984  7648 14417 14047  8479  4992 13874 11958 14500  4419  2717
  4189  5145  6732 12454  3007  3769  5913  4076 10055  8046 12865  8355
  6052  5652  9150 12987 14282 10300  9475  2268 12555  8251]

Column :CoapplicantIncome
[    0.  1500.  2358.  4196.  1516.  2504. 10968.   700.  8106.  2840.
  3500.  2253.  1040.  2925.  1400.  2033.  2669.  1850.  2667.  1305.
  6733.  6335.  5963.  2209.   555.  3286.  3908.  6981.   947.  2518.
   537.  6366.  3989.  3894.  5404.  3397.  6574.  2242.  2754.  5808.
  5357.  3023.  7708.   185.    44.  2097.  1980.  1927.  1330.  3711.
  3658.   794.  6216.    91.  1942.  7368.  4076.    65.    73.  5922.
  6032.  5412.  1998.  1595.   644.  1867.  6588.  4728.   204.   445.
  5918.  6386.  2715.  1672.  3230.  4492.   275.  6964.  7960.  4716.
  6047.  1666.  3190.  3724.  5123.  7700.    67.  4645.   849.  3348.
  2404.  1035.  7678.   885.  1649.  2644.  3255.  2223.  5256.  1115.
  5569.  2310.  2267.  5151.  3538.   319.  2997.  1532.   821.   553.
  7992.  3893.  7335.  7672.  6278.  3357.   733.  6990.  3719.  1406.
  2812.  6045.  1452.  2758.  4783.  2436.  3727.  4981.  3931.  2764.
  3041.  2231.  3970.  6555.   829.  4238.  5356.  3635.   518.   789.
   803.  4137.  4546.  4816.   941.  1026.  3542.  4039.  1369.  3660.
  3683.  5514.  4486.  4248.  4500.  1657.  7225.  6033.  7243.  7563.
  6947.   770.  5327.  2074.  6065.   511.  4537.  6052.  4259.  2045.
  5458.  6716.  5163.  5358.  4146.  3759.  2551.  5359.   492.  2949.
  3774.  7587.  4819.   857.  6659.  6728.  4886.  5103.  6174.  5555.
  3457.  1028.  2510.  3659.  1811.  1804.  4827.  1523.   408.   746.
  6643.  7833.  4962.   101.  3131.  1674.  2854.  7034.   259.  1956.
  3513.  3204.  6961.  6989.   156.  3528.  1891.  6608.  7950.  1226.
  6946.  1358.   231.  4596.   191.  7037.    54.  1439.  7001.  5072.
   778.  6225.  2639.  4060.]

Column :LoanAmount
[128  66 120 141 267  95 158 168 349  70 100 200 114 104 115 122 110  35
 150 113  90 130 312 192 162 140  96 180 135 254 160 270 315 187 248  36
 266  37 329 205  94  76  43 236 242 398 301 210  79  82 251 350  62 239
 169 355 154 156 358 320 139 105 182  83 371 268 280 344 302 392 230  84
  65 393 142  59 194 351 345 215  39  58 197 193  51 190  47  46  54 167
 119 206  85  63 339 249 127 189 362 284 159 294 379 253 289 318 356 171
  57 387  72 185 269 382  53  44 335 152 173 176 198 148  40 261 228 126
 245 375 174 220 399 172 224 237 342 214 331 179 123 305  97  75 391 389
 217 303 143 290 316 101 216 233 201  61  86  55 212  91 272 109 372 209
 195 309 282  60 199 203  89 296 368 286 181 256 108 263  67 116 291 103
  33 394 341 363 133 134 259 364 222 219 153  52 304 377  64  45  48 396
 390  30 306 281 226 311 295  77 279  73 285 157 383 238 241 258 165 397
 137  34 277 161 117 106 166 338 325  93 252 170 149 211 359 204 274 218
 146 275 244  42 322 346 257 313 132 240 374  69 202 278 283 400 343 118
 373 365 184  78 191 334 327 177 229]

Column :Loan_Amount_Term
[360 300 180 240]

Column :Credit_History
[1 0]

Column :Property_Area
['Urban' 'Rural' 'Semiurban']

Column :Loan_Status
[1 0]

Column :Total_Income
[ 4583.  4500.  4941.  6000.  9613.  3849.  5540.  4006. 23809.  3900.
  2500. 11179.  4693.  4400.  7660.  6100.  5052.  5266.  1442.  3750.
  6425.  4286.  4416. 10750.  2100.  6556.  4600.  4350.  8334.  3200.
  2400.  3800.  5000.  7970.  8181.  5564. 11734. 17214. 14848. 13513.
 17410. 12618.  6003.  5782.  9316.  9723. 16615. 16504.  8532.  9266.
  7117. 15010. 12631.  8950. 14021. 18576.  9895. 20154.  1525.  5138.
 20875. 17556.  8996.  5251.  9866. 13833.  7881.  5628. 11495.  7375.
 11162.  7617. 14211. 15855.  3265. 13926. 13766.  4537.  4091.  9290.
  2357. 14222.  4296. 12231. 10367.  1507.  4651.  7432. 11911. 11331.
  3874. 16617.  6975.  5777. 10982.  5814.  6692.  4930. 11601. 12810.
 13389.  4902. 14594.  9165. 12988. 12107. 19213.  8010.  9193.  4108.
 11818.  3497.  8497.  1906.  5125. 13187. 19323.  9920. 12145. 12229.
  1759. 10847. 16206. 11532. 13943.  5404.  4362. 14865. 10571. 12486.
 14797. 10880. 10257.  6643.  7876.  9052.  7956. 11451.  3302. 10514.
 15798. 10473. 11660. 13885. 14452.  4298. 12078.  8200.  4679.  9312.
 13711. 13727. 15269. 19154. 10389. 11136. 12142. 11351. 12022.  3502.
  3303.  4473. 11722.  2917.  3843. 11863. 11600. 13368.  6417. 13944.
  8065. 10659.  6018. 14793. 10315. 13129. 13417.  4976. 11114.  5355.
  2413. 15981. 13416.  7708. 16682. 11597.  9725.  6209.  2589.  5015.
 13185.  5485. 13580. 14952.  8578. 12871. 11175. 14796.  5471. 10635.
  5376. 14607. 12427.  7892.  9448. 10785.  6036.  2742. 20354. 20452.
  6393. 17777.  6712. 14073.  8341. 21276.  6632.  9399. 10720. 14225.
  8376. 14690. 12703.  9782. 11328.  7317. 11036. 13197.  2166. 13065.
  9827. 15306.  9640. 13426. 17432.  4890.  6523. 11479. 17676.  8813.
  4067.  6642.  6532.  3429. 14976.  8120. 10441.  5510. 14114. 11814.
  3621. 13752. 11276. 14464. 17794.  7444. 17707.  6395. 10049.  7523.
  6283.  8440. 11928. 16878.  8938.  7988. 14383.  1653.  9137. 17130.
  4015. 11561. 17910. 13543.  3889. 12052.  5481. 12222.  7819. 15092.
  3718.  1520.  5407. 19338.  6653.  6411. 17506.  5066. 17329. 14719.
 12895. 16901. 12506. 10926. 11559. 22146.  9427. 13778.  7275. 12302.
 10044.  9413. 13515. 20318.  2354.  4742. 12116.  2919. 18617. 11604.
 14155. 11909. 16759. 21051. 12293. 15167.  2929. 15797.  2032. 18199.
  8282.  2972.  9979.  4012.  8655.  5222.  2900.  9648. 10023.  2451.
 12876.  5563. 21129. 17514.  7997. 14883.  2587.  7727.  2280. 12508.
 21486. 14792. 15056.  8849. 10343.  9691. 10379.  5960.  2250. 17126.
 13288. 13091.  5651.  8692. 15125. 12001.  3929.  9226.  7987.  8318.
  6979.  5613.  7728. 12322.  5585. 12455.  3908. 10302.  8177.  3826.
  6870.  4878.  9248.  2208. 15467. 14475.  6873. 11105.  8286.  9354.
  5923. 12025.  4491. 11657. 14382.  8607.  7285.  7383. 11433.  7537.
 16602.  2717.  1696.  6930.  8856. 13133.  2984. 15598. 14417. 15273.
  8479.  4992. 20820. 11958. 15858.  4650.  8785.  5145.  6923. 19491.
  3007.  3769.  5913.  4130. 11494.  8046. 19866. 13427.  6052.  5652.
  9928. 19212. 14355. 10300. 12114.  2268. 12555. 12311.]

Column :Income_to_Loan_Ratio
[ 35.52713178  67.1641791   40.83471074  42.25352113  35.86940299
  40.09375     34.8427673   23.70414201  68.02571429  54.92957746
  24.75247525  55.61691542  40.80869565  36.36363636  72.95238095
  52.5862069   41.07317073  47.44144144  40.05555556  30.99173554
  42.54966887  39.47368421  47.0989011   33.70992366  34.34504792
  10.88082902  40.2208589   32.62411348  44.84536082  46.0441989
  26.44628099  44.11764706  23.76237624  34.23423423  33.11258278
  31.25490196  50.8136646   20.53136531  37.13291139  91.56382979
  59.63052209 365.21621622  65.20599251 332.05263158  18.19090909
  28.06796117  80.31034483 102.34736842 164.5049505  214.33766234
 193.90909091  39.09704641  29.28806584 156.35416667  31.6566416
  29.63576159  66.45023697 232.2        119.21686747  79.97619048
   4.34472934  44.29310345  68.03174603  86.97916667 103.27058824
  25.26966292  33.87741935  62.84076433  38.53203343  24.55140187
  40.2        108.44339623  40.30054645 132.88095238  20.47580645
  52.82899628  56.42348754  32.32673267  40.36521739  39.33142857
  14.97359736  10.40966921 130.84507042  10.2034632   87.25153374
  50.54117647 115.38679245  42.66255144   4.81469649  70.46969697
  18.86294416  83.29370629 188.85        19.86666667  47.20738636
  20.15895954  26.74537037 274.55        19.25165563 113.42372881
  61.625       58.59090909  54.05063291  69.01546392  94.26923077
  76.40837696 190.9375     111.96551724 257.59574468 349.32727273
  47.67857143  76.60833333  19.84541063 137.41860465  54.640625
  24.99117647   7.624       40.0390625   69.40526316 241.5375
  27.32782369  42.61403509  76.43125      5.96271186  28.54473684
  63.80314961  39.76551724 290.47916667  16.94043887 121.16666667
  41.63865546  61.45930233 145.18604651 255.12068966 131.08433735
  28.25619835  17.12113402 107.89041096  48.66666667  36.83333333
  42.41111111  91.72222222  27.45169713 292.55555556  61.60588235
 259.11111111  97.78169014  43.01190476  28.09150327 317.84210526
  47.12643678  26.43502825  97.          64.98104265  68.9798995
 102.47651007 467.17073171  39.65267176  48.62882096  95.60629921
  46.14227642  31.97340426  20.01142857  32.7029703   20.239819
  49.45991561   7.2925      22.21387283  52.72444444  65.53672316
  56.16806723  18.70845481 211.27272727  37.51162791  53.56281407
  42.38028169 133.27027027  31.06927711  72.93888889  83.85625
  35.54285714  89.62903226  17.5          7.31212121 163.07142857
 176.52631579  19.66326531  42.77435897  67.4244186  176.81818182
  28.48165138  12.56796117  16.49671053  34.42558747  38.09027778
  46.66666667 155.75        27.05993691 126.18627451  51.49769585
  37.93846154  23.38034188  32.22727273  26.61386139 235.59677419
 142.83908046 140.92857143  44.35680751  55.59278351  65.60869565
  10.04395604 185.03636364  54.8310992   30.44285714 296.28333333
  17.99463807  71.80102041  81.7745098  125.15294118  21.39354839
  33.21201413 181.69491525  41.47230321  41.46534653  60.4526749
  69.41530055  46.36018957  47.59663866  38.92021277 180.91803279
  65.985       10.61764706 104.43333333  43.98989899  41.28991597
  41.4796748   33.58885017  73.76923077  67.82879377  23.62318841
 125.44230769 105.31192661  66.95454545 129.60294118  34.76068376
 174.78947368  25.41634241  13.93902439 178.28571429  27.80821918
  57.36813187  52.98076923 155.0989011  347.47058824   9.16708861
  40.21052632  58.12371134  39.73626374 132.79104478  55.14074074
 229.96103896  24.59615385  25.1225      20.6109589   28.17488789
  30.03558719  54.21818182 162.28846154  66.70149254  51.87012987
 271.37735849  10.33125     46.85641026  56.53465347  36.17117117
  37.90491803  47.38095238 208.35384615  10.71349862 262.
 116.61702128 249.42857143  19.69521411  38.59846547  66.39285714
   5.24137931 174.41935484  62.99022801  28.43162393  65.41836735
  67.33076923  17.96453901  76.33920705 104.39007092  45.72695035
  54.16987179  91.95588235  36.91216216  52.30316742 283.92307692
 196.39583333  40.28654971  25.98214286 166.24324324 186.
  29.32398754  47.25524476 307.84848485  14.89873418  30.59354839
  31.55208333  17.375       33.51464435 100.09139785  47.95041322
  62.35682819  45.98069498  48.57681159  83.53571429 261.55319149
  91.36746988  16.5480226   54.09931507  30.78787879  46.42602041
  20.80904523  21.53623188  32.19032258 114.62857143 211.09756098
  37.03546099  10.43165468  59.55555556 208.8125      15.41509434
 109.11864407  25.75462963 197.46728972 104.8742515   22.40056022
  43.90265487  28.74444444  23.70245399  24.25531915 128.94845361
  84.92490119  86.50292398 100.37333333  40.04072398  48.78773585
  26.91944444  50.62926829 110.37037037   8.18181818  78.20091324
 174.84210526  50.54440154  53.81904762  39.33031674  69.70046083
  42.70818505  12.9669967   25.34615385  54.33333333  78.49009901
 140.98305085  24.4877193   15.63509749 161.          56.00909091
  20.23550725  90.25362319  24.425       27.11052632  33.3755102
  49.05128205 159.76744186  15.10216718  33.50724638   6.36311239
 103.11333333  56.10465116  21.88853503 100.04504505  62.30075188
  68.77941176  76.92207792  49.89626556  22.91326531  31.08533333
  58.70204082  78.96330275  83.73563218  19.2265625  163.32857143
  37.12807882  47.16477273   9.73835125   5.97183099  30.
  35.00395257  32.75062344  15.4611399   49.99358974  76.68617021
 381.825       73.09482759  17.95683453  60.52325581  48.6097561
  39.94458438  39.07563025   7.26470588  39.75113122  22.86666667
  18.91530055  66.97938144  51.84482759  20.37297297  43.8
  10.40302267  32.74643875 101.84810127 103.46875     40.08059701
  18.45121951  28.26        66.63087248  49.01020408  80.64606742
  44.7826087   33.09836066  15.22147651 193.15384615  35.68405797]

Column :Loan_Burden
[0.02792321 0.01466341 0.02428167 0.02349608 0.027772   0.02467532
 0.02851471 0.04192663 0.01465771 0.01794412 0.03998401 0.01788909
 0.02428632 0.02726653 0.01357525 0.01884937 0.02414407 0.02088475
 0.02425502 0.03199147 0.02334267 0.02510553 0.0209937  0.02943174
 0.02902056 0.09138505 0.02470642 0.03042817 0.02206389 0.02159568
 0.03748828 0.02249625 0.04164931 0.02893975 0.029994   0.03186551
 0.01955512 0.04851752 0.02684278 0.01086262 0.01670146 0.0026639
 0.0152777  0.00293209 0.0547968  0.03544873 0.01234303 0.0096668
 0.0060183  0.00460467 0.00503926 0.02546671 0.03399831 0.00632869
 0.03150728 0.03362753 0.01497647 0.00425257 0.00828618 0.01245349
 0.2293578  0.02237789 0.01446233 0.01144855 0.00962579 0.0394576
 0.02932216 0.01581028 0.02587827 0.04059883 0.02469355 0.00913361
 0.02467462 0.00743528 0.04870045 0.0188573  0.01765893 0.03061849
 0.02470022 0.02535048 0.06654914 0.09579668 0.00753417 0.09754029
 0.01139    0.01954852 0.00858404 0.02334105 0.20689655 0.01397248
 0.05287233 0.01192075 0.00520649 0.05006452 0.02112168 0.04945528
 0.03721011 0.00355094 0.05176268 0.00866577 0.01602109 0.01697983
 0.01842167 0.01441374 0.01040179 0.01301816 0.00512765 0.00885365
 0.00379914 0.00281045 0.02084634 0.01294322 0.05013385 0.00719181
 0.01801029 0.03989174 0.13057158 0.02477565 0.01433121 0.00408818
 0.03648826 0.02338218 0.01300082 0.16704545 0.03493732 0.01561054
 0.02505853 0.00337063 0.05883441 0.008022   0.02394726 0.0161748
 0.00680708 0.00385187 0.00753607 0.03528953 0.05824804 0.00914054
 0.02043521 0.02702023 0.02348935 0.01059643 0.03632905 0.00335464
 0.01613519 0.00377326 0.01015411 0.02317858 0.03535706 0.00306317
 0.02109499 0.03760684 0.01020079 0.01531505 0.01442308 0.00969221
 0.00208823 0.02512031 0.0204723  0.01037635 0.0215821  0.03119022
 0.04967171 0.03026634 0.049173   0.02013137 0.13673749 0.04474506
 0.01888065 0.01517111 0.01772758 0.05328763 0.00466117 0.02653112
 0.01857411 0.02342582 0.00743545 0.03208608 0.0136329  0.01184975
 0.02792847 0.01106613 0.05694548 0.13628832 0.00606933 0.00558992
 0.05071994 0.02331715 0.01474392 0.00555213 0.03494364 0.07915058
 0.0604067  0.02897012 0.02606635 0.02135336 0.00635324 0.03683413
 0.00784649 0.01932713 0.02628911 0.04258041 0.03093268 0.03738144
 0.00417579 0.00691986 0.0069682  0.02243624 0.01789357 0.01507371

In [478]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
df = df.drop("ApplicantID", axis=1)

In [479]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]


numcols = X.select_dtypes(include=["int64","float64"]).columns
catcols = X.select_dtypes(include=["object"]).columns

In [480]:
numtr = Pipeline(steps = [
    ("imputer", SimpleImputer(strategy='median')),
    ("Scaler", StandardScaler())
])
cattr = Pipeline(steps = [
    ("imputer", SimpleImputer(strategy='most_frequent')),
    ("encoder1", OneHotEncoder(handle_unknown='ignore'))
])
Preprocessor = ColumnTransformer(
    transformers=[
        ("num",numtr,numcols),
        ("cat",cattr,catcols)
    ])

In [481]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [482]:
model = Pipeline(steps=[
    ("preprocessing", Preprocessor),
    ("classifier", RandomForestClassifier(class_weight="balanced",random_state=42))
])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [483]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.5632183908045977
              precision    recall  f1-score   support

           0       0.47      0.57      0.51        35
           1       0.66      0.56      0.60        52

    accuracy                           0.56        87
   macro avg       0.56      0.56      0.56        87
weighted avg       0.58      0.56      0.57        87

In [484]:
from xgboost import XGBClassifier
model2 = Pipeline(steps=[
    ('preprocessing', Preprocessor),
    ('classifier', XGBClassifier( n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=42))
])
model2.fit(X_train, y_train)
y2_pred = model2.predict(X_test)

In [485]:
pg = {
    'classifier__n_estimator':[100,300],
    'classifier__max_depth':[3,5,7],
    'classifier__learning_rate':[0.01,1.0],
    'classifier__subsamples':[0.8,1]
}
model2.named_steps['classifier'].feature_importances_

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model2, X, y, cv=5)
print(scores.mean())

0.5103448275862069

In [486]:
# numeric features (unchanged names)
num_features = numcols

# categorical features (from OneHotEncoder)
cat_features = model2.named_steps["preprocessing"] \
    .named_transformers_["cat"] \
    .named_steps["encoder1"] \
    .get_feature_names_out(catcols)

# combine
features = np.concatenate([num_features, cat_features])

# importance from model
importance = model2.named_steps["classifier"].feature_importances_

# dataframe
import pandas as pd

feature_importance_df = pd.DataFrame({
    "Feature": features,
    "Importance": importance
}).sort_values(by="Importance", ascending=False)

feature_importance_df

                    Feature  Importance
3                LoanAmount    0.068545
11               Married_No    0.068197
0                Dependents    0.067917
14   Education_Not Graduate    0.057498
2         CoapplicantIncome    0.053990
6              Total_Income    0.053929
1           ApplicantIncome    0.053438
8               Loan_Burden    0.053127
7      Income_to_Loan_Ratio    0.052149
15          SelfEmployed_No    0.049983
5            Credit_History    0.049147
4          Loan_Amount_Term    0.049033
18  Property_Area_Semiurban    0.046384
12              Married_Yes    0.043205
16         SelfEmployed_Yes    0.043191
19      Property_Area_Urban    0.042815
13       Education_Graduate    0.042274
9             Gender_Female    0.039079
17      Property_Area_Rural    0.037314
10              Gender_Male    0.028784

In [487]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.5632183908045977

Classification Report:

              precision    recall  f1-score   support

           0       0.47      0.57      0.51        35
           1       0.66      0.56      0.60        52

    accuracy                           0.56        87
   macro avg       0.56      0.56      0.56        87
weighted avg       0.58      0.56      0.57        87


Confusion Matrix:

[[20 15]
 [23 29]]

In [488]:
scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")
print("\nCV Accuracy Mean:", scores.mean())

# -------------------------
# 13. OPTIONAL: PROBABILITY THRESHOLD TUNING
# -------------------------
probs = model.predict_proba(X_test)[:, 1]
custom_pred = (probs > 0.4).astype(int)

print("\nCustom Threshold Accuracy (0.4):", accuracy_score(y_test, custom_pred))

CV Accuracy Mean: 0.496551724137931

Custom Threshold Accuracy (0.4): 0.6436781609195402

In [489]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [491]:
log_model = Pipeline([
    ("preprocessing", Preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

print("🔵 Logistic Regression Results")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))
print(confusion_matrix(y_test, y_pred_log))

🔵 Logistic Regression Results
Accuracy: 0.5517241379310345
              precision    recall  f1-score   support

           0       0.45      0.54      0.49        35
           1       0.64      0.56      0.60        52

    accuracy                           0.55        87
   macro avg       0.55      0.55      0.55        87
weighted avg       0.57      0.55      0.56        87

[[19 16]
 [23 29]]

In [492]:
svm_model = Pipeline([
    ("preprocessing", Preprocessor),
    ("classifier", SVC(kernel="rbf", probability=True))
])

svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

print("🟢 SVM Results")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))

🟢 SVM Results
Accuracy: 0.6206896551724138
              precision    recall  f1-score   support

           0       0.52      0.69      0.59        35
           1       0.73      0.58      0.65        52

    accuracy                           0.62        87
   macro avg       0.63      0.63      0.62        87
weighted avg       0.65      0.62      0.62        87

[[24 11]
 [22 30]]

In [493]:
models = {
    "Logistic Regression": log_model,
    "SVM": svm_model,
    "XGBoost": model
}

for name, m in models.items():
    pred = m.predict(X_test)
    print("\n", name)
    print("Accuracy:", accuracy_score(y_test, pred))

 Logistic Regression
Accuracy: 0.5517241379310345

 SVM
Accuracy: 0.6206896551724138

 XGBoost
Accuracy: 0.5632183908045977

In [494]:
import pandas as pd

def predict_all_models(data_dict):

    # convert dictionary → dataframe
    input_df = pd.DataFrame([data_dict])

    results = {}

    # Logistic Regression
    results["Logistic Regression"] = log_model.predict(input_df)[0]

    # SVM
    results["SVM"] = svm_model.predict(input_df)[0]

    # XGBoost
    results["XGBoost"] = model.predict(input_df)[0]

    return results

new_loan = {
    "Gender": "Male",
    "Married": "Yes",
    "Dependents": 2,
    "Education": "Graduate",
    "SelfEmployed": "No",
    "ApplicantIncome": 6000,
    "CoapplicantIncome": 1500,
    "LoanAmount": 200,
    "Loan_Amount_Term": 360,
    "Credit_History": 1,
    "Property_Area": "Urban",
    "Total_Income": 7500,
    "Income_to_Loan_Ratio": 7500/200,
    "Loan_Burden": 200/7500
}

result = predict_all_models(new_loan)

print("Model Predictions:")
for model_name, pred in result.items():
    status = "Approved" if pred == 1 else "Rejected"
    print(f"{model_name}: {status}")
    
def predict_all_with_proba(data_dict):

    input_df = pd.DataFrame([data_dict])

    results = {}

    results["Logistic Regression"] = log_model.predict_proba(input_df)[0][1]
    results["SVM"] = svm_model.predict_proba(input_df)[0][1]
    results["XGBoost"] = model.predict_proba(input_df)[0][1]

    return results

Model Predictions:
Logistic Regression: Approved
SVM: Approved
XGBoost: Approved